/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe_example_registration_form;

/**
 *
 * @author dylan
 */
public class Registration_Form extends javax.swing.JFrame {

    /**
     * Creates new form Registration_Form
     */
    public Registration_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel1_Title = new javax.swing.JLabel();
        jLabel1_name = new javax.swing.JLabel();
        jLabel1_Gender = new javax.swing.JLabel();
        jLabel1_Mobile = new javax.swing.JLabel();
        jLabel1_DOB = new javax.swing.JLabel();
        jLabel1_Address = new javax.swing.JLabel();
        jTextField_name = new javax.swing.JTextField();
        jTextField_mobile = new javax.swing.JTextField();
        jTextField_address = new javax.swing.JTextField();
        jRadioButton_Male = new javax.swing.JRadioButton();
        jRadioButton_female = new javax.swing.JRadioButton();
        jComboBox_Days = new javax.swing.JComboBox<>();
        jComboBox_Months = new javax.swing.JComboBox<>();
        jComboBox_Year = new javax.swing.JComboBox<>();
        jCheckBox_Terms = new javax.swing.JCheckBox();
        jButton_Submit = new javax.swing.JButton();
        jButton_Reset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Error = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration Form");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        jLabel1_Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1_Title.setText("Registration Form");

        jLabel1_name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1_name.setText("Name ");

        jLabel1_Gender.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1_Gender.setText("Gender");

        jLabel1_Mobile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1_Mobile.setText("Mobile");

        jLabel1_DOB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1_DOB.setText("DOB");

        jLabel1_Address.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1_Address.setText("Address");

        buttonGroup5.add(jRadioButton_Male);
        jRadioButton_Male.setText("Male");

        buttonGroup5.add(jRadioButton_female);
        jRadioButton_female.setText("Female");

        jComboBox_Days.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jComboBox_Months.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        jComboBox_Year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059", "2060", "2061", "2062", "2063", "2064", "2065", "2066", "2067", "2068", "2069", "2070", "2071", "2072", "2073", "2074", "2075", "2076", "2077", "2078", "2079", "2080", "2081", "2082", "2083", "2084", "2085", "2086", "2087", "2088", "2089", "2090", "2091", "2092", "2093", "2094", "2095", "2096", "2097", "2098", "2099", "2100" }));
        jComboBox_Year.setSelectedIndex(124);

        jCheckBox_Terms.setText("Accept Terms And Conditions.");

        jButton_Submit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton_Submit.setText("Submit");
        jButton_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SubmitActionPerformed(evt);
            }
        });

        jButton_Reset.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton_Reset.setText("Reset");
        jButton_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ResetActionPerformed(evt);
            }
        });

        jTextArea_Error.setColumns(20);
        jTextArea_Error.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Error);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_Submit)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Reset))
                            .addComponent(jCheckBox_Terms, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1_DOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1_Address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_address)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox_Days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox_Months, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1_Gender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(jLabel1_Mobile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton_Male, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton_female, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_name)
                            .addComponent(jLabel1_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_mobile)
                            .addComponent(jLabel1_Mobile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1_Gender)
                            .addComponent(jRadioButton_Male)
                            .addComponent(jRadioButton_female))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1_DOB)
                            .addComponent(jComboBox_Days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_Months, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1_Address)
                            .addComponent(jTextField_address, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox_Terms)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Submit)
                            .addComponent(jButton_Reset))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SubmitActionPerformed
        // TODO add your handling code here:
        
    //*************************************************//
    // Retrieve values from the form
    String name = jTextField_name.getText().trim();
        if(name.isBlank() || name.isEmpty())
        {
            jTextArea_Error.setText("Please enter your name");
            return;  // Stop execution and diplay error message
        }
    String mobile = jTextField_mobile.getText().trim();
        if(mobile.isBlank() || mobile.isEmpty() || mobile.length() != 10)
        {
            jTextArea_Error.setText("Please enter your full mobile number\nYour number should be 10 characters long\nbut yours is only : " 
                    + mobile.length());
            return;  // Stop execution and diplay error message
        }
    String address = jTextField_address.getText().trim();
        if(address.isBlank() || address.isEmpty())
        {
            jTextArea_Error.setText("Please enter your address");
            return;  // Stop execution and diplay error message
        }
    //*************************************************//
    
    //*************************************************//
    // Determine gender
    String gender;
    if (jRadioButton_Male.isSelected()) {
        gender = "Male";
    } else if (jRadioButton_female.isSelected()) {
        gender = "Female";
    } else {
        jTextArea_Error.setText("Please select a gender to continue");
        return;  // Stop execution and diplay error message
    }
    //*************************************************//

    //*************************************************//
    // Get DOB
    String day = (String) jComboBox_Days.getSelectedItem();
        if(day.isBlank() || day.isEmpty())
        {
            jTextArea_Error.setText("Please select the day you were born.");
            return;  // Stop execution and diplay error message
        }
    
    String month = (String) jComboBox_Months.getSelectedItem();
        if(month.isBlank() || month.isEmpty())
        {
            jTextArea_Error.setText("Please select the month you were born.");
            return;  // Stop execution and diplay error message
        }
    String year = (String) jComboBox_Year.getSelectedItem();
        if(year.isBlank() || year.isEmpty())
        {
            jTextArea_Error.setText("Please select the year you were born.");
            return;  // Stop execution and diplay error message
        }
    String dob = day + " " + month + " " + year;
    //*************************************************//

    //*************************************************//
    // Check if terms are accepted
    boolean acceptedTerms = jCheckBox_Terms.isSelected();
    // Error handling if terms not accepted
    if (!acceptedTerms) {
        jTextArea_Error.setText("Please accept the terms and conditions.");
        return;  // Stop execution if terms are not accepted
    }
    //*************************************************//

    //*************************************************//
    // Create a new Registered object
    Registered registeredUser = new Registered(name, mobile, gender, dob, address);
    //*************************************************//
    
    //*************************************************//
    // Clear the error message
    jTextArea_Error.setText("");
    //*************************************************//

    //*************************************************//
    //add to array
    Main main = new Main();
    main.addRegistered(registeredUser);
    //*************************************************//
        
    }//GEN-LAST:event_jButton_SubmitActionPerformed

    private void jButton_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ResetActionPerformed
        // TODO add your handling code here:
        
        //*************************************************//
        //set error message to blank text
        jTextArea_Error.setText("");
        //*************************************************//
        
        //*************************************************//
        //set name to blank text
        jTextField_name.setText("");
        //*************************************************//
        
        //*************************************************//
        //set mobile text to blank
        jTextField_mobile.setText("");
        //*************************************************//
        
        //*************************************************//
        //set address to blank
        jTextField_address.setText("");
        //*************************************************//
        
        //*************************************************//
        //set Gender buttons to false
        buttonGroup5.clearSelection();
        //*************************************************//
        
        //*************************************************//
        //set DOB to defualt
        jComboBox_Days.setSelectedIndex(0);
        jComboBox_Months.setSelectedIndex(0);
        jComboBox_Year.setSelectedIndex(124);
        //*************************************************//
        
        //*************************************************//
        //set TOS to false
        jCheckBox_Terms.setSelected(false);
        //*************************************************//
    }//GEN-LAST:event_jButton_ResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton_Reset;
    private javax.swing.JButton jButton_Submit;
    private javax.swing.JCheckBox jCheckBox_Terms;
    private javax.swing.JComboBox<String> jComboBox_Days;
    private javax.swing.JComboBox<String> jComboBox_Months;
    private javax.swing.JComboBox<String> jComboBox_Year;
    private javax.swing.JLabel jLabel1_Address;
    private javax.swing.JLabel jLabel1_DOB;
    private javax.swing.JLabel jLabel1_Gender;
    private javax.swing.JLabel jLabel1_Mobile;
    private javax.swing.JLabel jLabel1_Title;
    private javax.swing.JLabel jLabel1_name;
    private javax.swing.JRadioButton jRadioButton_Male;
    private javax.swing.JRadioButton jRadioButton_female;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_Error;
    private javax.swing.JTextField jTextField_address;
    private javax.swing.JTextField jTextField_mobile;
    private javax.swing.JTextField jTextField_name;
    // End of variables declaration//GEN-END:variables
}
