/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//**************************************************************************************//
package Question_2;
//*************************************************//

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;


/**
 *
 * @author dylan
 */
//*************************************************//
public class MovieTicketData extends javax.swing.JFrame {
    //*************************************************//
    /**
     * Creates new form MovieTicketData
     */
    public MovieTicketData() {
        initComponents();
    }
    //*************************************************//
    
    //*************************************************//
    //declare method class
    MovieTickets tickets = new MovieTickets();
    //*************************************************//
    
    //*************************************************//
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMovie = new javax.swing.JLabel();
        lblNumberOfTickets = new javax.swing.JLabel();
        lblTicketPrice = new javax.swing.JLabel();
        lblTicketReport = new javax.swing.JLabel();
        cmbMovieList = new javax.swing.JComboBox<>();
        txtNumberOfTickets = new javax.swing.JTextField();
        txtTicketPrice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaReport = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnProcess = new javax.swing.JMenuItem();
        btnClear = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MOVIE TICKETS");

        lblMovie.setText("MOVIE:");

        lblNumberOfTickets.setText("NUMBER OF TICKETS:");

        lblTicketPrice.setText("TICKET PRICE: ");

        lblTicketReport.setText("TICKET REPORT:");

        cmbMovieList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Napoleon", "Oppenheimer", "Damsel" }));

        txaReport.setEditable(false);
        txaReport.setColumns(20);
        txaReport.setRows(5);
        jScrollPane1.setViewportView(txaReport);

        jMenu1.setText("File");

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jMenu1.add(btnExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });
        jMenu2.add(btnProcess);

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jMenu2.add(btnClear);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNumberOfTickets, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(lblTicketPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMovie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTicketReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbMovieList, 0, 189, Short.MAX_VALUE)
                            .addComponent(txtNumberOfTickets)
                            .addComponent(txtTicketPrice))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMovie)
                    .addComponent(cmbMovieList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumberOfTickets)
                    .addComponent(txtNumberOfTickets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTicketPrice)
                    .addComponent(txtTicketPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblTicketReport)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //**************************************************************************************//
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        
        //*************************************************//
        //code to execute when the 'Exit' button is pressed to exit the program
        System.exit(0);
        //*************************************************//
    }//GEN-LAST:event_btnExitActionPerformed
    //**************************************************************************************//
    
    //**************************************************************************************//
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        
        //*************************************************//
        //this code to to reset the GUI when the 'Clear' button is pressed
        cmbMovieList.setSelectedIndex(0);
        txtNumberOfTickets.setText("");
        txtTicketPrice.setText("");
        txaReport.setText("");
        //*************************************************//
    }//GEN-LAST:event_btnClearActionPerformed

    //**************************************************************************************//
    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        
    //*************************************************//
    //this button will process the data
        
        //*************************************************//
        //first confirm that all the variables contain values
        
        //check all values are present
        boolean validate = tickets.ValidateData(this);
        
        //validate respone 
        if(validate)
        {
            //*************************************************//
            //process the data to the report screen
            String message = ProcessDataToReportScreen();
            txaReport.setText(message);
            //*************************************************//
            
            //*************************************************//
            //save data to the text file
            SaveDataToATextFile();
            //*************************************************//
        }
        else
        {
            //*************************************************//
            //if_ the validation fales, display error message and return to program
            txaReport.setText("Error, all values and fields must contain values");
            //*************************************************//
        }
        //*************************************************//
        
        
    
    //*************************************************//
    }//GEN-LAST:event_btnProcessActionPerformed
    //**************************************************************************************//
    
    //*************************************************//
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieTicketData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieTicketData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieTicketData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieTicketData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieTicketData().setVisible(true);
            }
        });
    }
    //*************************************************//
    
//**************************************************************************************//
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnClear;
    private javax.swing.JMenuItem btnExit;
    private javax.swing.JMenuItem btnProcess;
    public javax.swing.JComboBox<String> cmbMovieList;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMovie;
    private javax.swing.JLabel lblNumberOfTickets;
    private javax.swing.JLabel lblTicketPrice;
    private javax.swing.JLabel lblTicketReport;
    private javax.swing.JTextArea txaReport;
    public javax.swing.JTextField txtNumberOfTickets;
    public javax.swing.JTextField txtTicketPrice;
    // End of variables declaration//GEN-END:variables

    //*************************************************//
    //update report Screen
    private String ProcessDataToReportScreen() {
        //*************************************************//
        //create string to return
        String message = "";
        int numberOfTickets = Integer.parseInt(txtNumberOfTickets.getText());
        double ticketPrice = Double.parseDouble(txtTicketPrice.getText());
        //*************************************************//
        
        //*************************************************//
        //populate message
        message += "MOVIE NAME: " + cmbMovieList.getSelectedItem().toString() + "\n";
        message += "MOVIE TICKET PRICE: R " + ticketPrice + "\n";
        message += "NUMBER OF TICKETS: " + numberOfTickets + "\n";
        
        message += "TOTAL TICKET PRICE: R " + tickets.CalculateTotalTicketPrice(numberOfTickets,ticketPrice);
        //*************************************************//
        
        //*************************************************//
        //return string 
        return message;
        //*************************************************//
    }
    //*************************************************//
    
//**************************************************************************************//

    //*************************************************//
    private void SaveDataToATextFile() {
        //*************************************************//
        //get all values before writing to a file
        String message = "MOVIE TICKET REPORT" + "\n";
        message += "*************************************************" + "\n";
        message += ProcessDataToReportScreen() + "\n";
        message += "*************************************************";
        //*************************************************//
        
        //*************************************************//
        try {
            //*************************************************//
            // Create a File object for the text file
            File file = new File("report.txt");
            //*************************************************//
            
            //*************************************************//
            // Pass the File object to the PrintWriter
            PrintWriter writer = new PrintWriter(file);
            //*************************************************//
            
            //*************************************************//
            // Write content to the file
            writer.println(message);
            //*************************************************//
            
            //*************************************************//
            // Close the writer
            writer.close();
            //*************************************************//
            
        } catch (FileNotFoundException e) {
            System.out.println(e);
        }
        //*************************************************//
        
    }
    //*************************************************//
}
//***********************************END OF FILE****************************************//

//*************************************************//
//Name: Dylan Shortt
//Student number: ST10438409
//Group: 4
//Module: PROG
//Module code: 6112
//Date: 2024/11/12
//*************************************************//