/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Question_3;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author dylan
 */
public class Snake_Information extends javax.swing.JFrame {

    /**
     * Creates new form Snake_Information
     */
    public Snake_Information() {
        initComponents();
        populateComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        lblSelectSnake = new javax.swing.JLabel();
        cmbSnakes = new javax.swing.JComboBox<>();
        btnProcess = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaListBox = new javax.swing.JTextArea();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Snake Information");

        lblSelectSnake.setText("Select Snake:");

        cmbSnakes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", " " }));

        btnProcess.setText("PROCESS");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txaListBox.setEditable(false);
        txaListBox.setColumns(20);
        txaListBox.setRows(5);
        jScrollPane1.setViewportView(txaListBox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSelectSnake, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbSnakes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectSnake)
                    .addComponent(cmbSnakes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcess)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //*************************************************//
    //method to read from the file 
    public static String findSnakeInfo(String snakeName) {
        
        //*************************************************//
        //create a string builder 
        StringBuilder result = new StringBuilder();
        //*************************************************//
        
        //*************************************************//
        //create a try and catch for reading from the file
        try (BufferedReader reader = new BufferedReader(new FileReader("snakes.txt"))) {
            
            //*************************************************//
            //declare var's
            String line;
            boolean found = false;
            int linesAfter = 0;
            //*************************************************//
            
            //*************************************************//
            //create while_ loop to search the text file
            while ((line = reader.readLine()) != null) {
                //*************************************************//
                //checking if_ the snake was found
                if (found) {
                    
                    //*************************************************//
                    //add the snake and the two lines below it to the file
                    result.append(line).append("\n");
                    linesAfter++;
                    //*************************************************//
                    
                    //*************************************************//
                    // Stop after two additional lines
                    if (linesAfter == 2) break;
                    //*************************************************//
                    
                    //*************************************************//
                    //checking for snake 
                } else if (line.trim().equalsIgnoreCase(snakeName)) {
                    //*************************************************//
                    // Add the snake name line
                    result.append(line).append("\n"); 
                    found = true;
                    //*************************************************//
                }
                //*************************************************//
            }
            //*************************************************//
            
            //*************************************************//
            //catch errors
        } catch (IOException e) {
            e.printStackTrace();
        }
        //*************************************************//
        
        //*************************************************//
        //return strinf of snake stuff
        return result.toString();
        //*************************************************//
    }
    //*************************************************//
    
    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        //*************************************************//
        //return values for list
        
        //get selected snake 
        String selectedSnake = cmbSnakes.getSelectedItem().toString();
        
        //get details 
        String message = findSnakeInfo(selectedSnake);
        
        //set list box to hold the snakes details
        txaListBox.setText(message);
        //*************************************************//
    }//GEN-LAST:event_btnProcessActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        //*************************************************//
        //clear the list box of snake information
        txaListBox.setText("");
        //*************************************************//
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Snake_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Snake_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Snake_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Snake_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Snake_Information().setVisible(true);
            }
        });
    }
    
    private void populateComboBox() {
    //*************************************************//
    // Create a DefaultComboBoxModel to hold the snake names
    DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
    //*************************************************//
    
    //*************************************************//
    // Try-catch block to handle file reading
    try (BufferedReader reader = new BufferedReader(new FileReader("snakes.txt"))) {
        String line;
        
        //*************************************************//
        // Read the file line by line
        while ((line = reader.readLine()) != null) {
            //*************************************************//
            // Check if the line is not empty and doesn't contain ranking/assistance info
            if (!line.trim().isEmpty() && !line.contains("Fatality Ranking") && !line.contains("Medical Assistance")) {
                model.addElement(line.trim()); // Add snake name to the combo box model
            }
            //*************************************************//
            
            //*************************************************//
            // Skip the next two lines after each snake name
            reader.readLine(); // Skip "Fatality Ranking" line
            reader.readLine(); // Skip "Medical Assistance" line
            //*************************************************//
        }
    //*************************************************//
    } catch (IOException e) {
        e.printStackTrace(); // Print any errors during file reading
    }
    //*************************************************//
    
    //*************************************************//
    // Set the model to the combo box to display the snake names
    cmbSnakes.setModel(model);
    //*************************************************//
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcess;
    private javax.swing.JComboBox<String> cmbSnakes;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblSelectSnake;
    private javax.swing.JTextArea txaListBox;
    // End of variables declaration//GEN-END:variables
}
