/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ice_6;

import javax.swing.JOptionPane;

/**
 *
 * @author dylan
 */
public class Dispatch_Item extends javax.swing.JFrame {

    /**
     * Creates new form Home_Page
     */
    public Dispatch_Item() {
        initComponents(); 
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_home = new javax.swing.JButton();
        jButton_Dispatch_item = new javax.swing.JButton();
        jButton_Stock = new javax.swing.JButton();
        jButton_View_records = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_title = new javax.swing.JTextArea();
        jLabel_mini_title = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_type = new javax.swing.JLabel();
        jComboBox_items = new javax.swing.JComboBox<>();
        jLabel_item_name = new javax.swing.JLabel();
        jTextField_item_name = new javax.swing.JTextField();
        jLabel_quantity = new javax.swing.JLabel();
        jTextField_item_quantity = new javax.swing.JTextField();
        jLabel_dispatch_row = new javax.swing.JLabel();
        jTextField_row = new javax.swing.JTextField();
        jButton_DISPATCH = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jButton_home.setBackground(new java.awt.Color(102, 102, 102));
        jButton_home.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_home.setForeground(new java.awt.Color(255, 255, 255));
        jButton_home.setText("Home");
        jButton_home.setBorder(null);
        jButton_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_homeActionPerformed(evt);
            }
        });

        jButton_Dispatch_item.setBackground(new java.awt.Color(102, 102, 102));
        jButton_Dispatch_item.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_Dispatch_item.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Dispatch_item.setText("Dispatch item");
        jButton_Dispatch_item.setBorder(null);
        jButton_Dispatch_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Dispatch_itemActionPerformed(evt);
            }
        });

        jButton_Stock.setBackground(new java.awt.Color(102, 102, 102));
        jButton_Stock.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_Stock.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Stock.setText("Stock");
        jButton_Stock.setBorder(null);
        jButton_Stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_StockActionPerformed(evt);
            }
        });

        jButton_View_records.setBackground(new java.awt.Color(102, 102, 102));
        jButton_View_records.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_View_records.setForeground(new java.awt.Color(255, 255, 255));
        jButton_View_records.setText("View records");
        jButton_View_records.setBorder(null);
        jButton_View_records.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_View_recordsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_View_records)
                    .addComponent(jButton_Stock)
                    .addComponent(jButton_Dispatch_item)
                    .addComponent(jButton_home))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jButton_home)
                .addGap(35, 35, 35)
                .addComponent(jButton_Dispatch_item)
                .addGap(35, 35, 35)
                .addComponent(jButton_Stock)
                .addGap(40, 40, 40)
                .addComponent(jButton_View_records)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        jTextArea_title.setEditable(false);
        jTextArea_title.setBackground(new java.awt.Color(255, 51, 51));
        jTextArea_title.setColumns(20);
        jTextArea_title.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextArea_title.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_title.setRows(1);
        jTextArea_title.setText("Stock management system for covid-19 essentials");
        jScrollPane2.setViewportView(jTextArea_title);

        jLabel_mini_title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_mini_title.setText("Dispatch Item");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Dispatch Item");

        jLabel_type.setText("Item type");

        jComboBox_items.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masks", "Hand sanitizers", "Face shields", "Disinfectant wipes" }));
        jComboBox_items.setToolTipText("");

        jLabel_item_name.setText("Item name");

        jLabel_quantity.setText("Quantity");

        jLabel_dispatch_row.setText("Dispatch to which row");

        jButton_DISPATCH.setText("DISPATCH");
        jButton_DISPATCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DISPATCHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_DISPATCH, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox_items, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_type, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_item_name, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_item_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_row))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel_item_name)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel_quantity)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addComponent(jLabel_dispatch_row)
                                .addGap(15, 15, 15)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_type)
                    .addComponent(jLabel_item_name)
                    .addComponent(jLabel_quantity)
                    .addComponent(jLabel_dispatch_row))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_items, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_item_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_item_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_row, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_DISPATCH, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_mini_title, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_mini_title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_homeActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_homeActionPerformed

    private void jButton_Dispatch_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Dispatch_itemActionPerformed
        // TODO add your handling code here:
        Dispatch_Item dispatch = new Dispatch_Item();
        dispatch.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_Dispatch_itemActionPerformed

    private void jButton_DISPATCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DISPATCHActionPerformed
        // TODO add your handling code here:
        
        //*************************************************//
        //ensure a item was selected
        String item = "" + jComboBox_items.getSelectedItem();
            if(item.isBlank() || item.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please select an item");
                return;
            }
        //*************************************************//
        
        //*************************************************//
        //check a name was entered
        String name = jTextField_item_name.getText();
         if(name.isBlank() || name.isBlank())
         {
             JOptionPane.showMessageDialog(null, "Please enter an item name");
             return;
         }
        //*************************************************//
        
        //*************************************************//
        //check a name was entered
        String quantity = jTextField_item_quantity.getText();
         if(quantity.isBlank() || quantity.isBlank())
         {
             JOptionPane.showMessageDialog(null, "Please enter an item quantity");
             return;
         }
        //*************************************************//
        
        //*************************************************//
        //check a name was entered
        String row = jTextField_row.getText();
         if(row.isBlank() || row.isBlank())
         {
             JOptionPane.showMessageDialog(null, "Please enter the row to be dispatched to");
             return;
         }
        //*************************************************//
        
        //*************************************************//
        //success
        JOptionPane.showMessageDialog(null, "Item dispatched!");
        
        Dispatch recive = new Dispatch(item, name, quantity, row);
        //*************************************************//
    }//GEN-LAST:event_jButton_DISPATCHActionPerformed

    private void jButton_StockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_StockActionPerformed
        // TODO add your handling code here:
        Stock stock = new Stock();
        stock.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_StockActionPerformed

    private void jButton_View_recordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_View_recordsActionPerformed
        // TODO add your handling code here:
        Records record = new Records();
        record.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_View_recordsActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_DISPATCH;
    private javax.swing.JButton jButton_Dispatch_item;
    private javax.swing.JButton jButton_Stock;
    private javax.swing.JButton jButton_View_records;
    private javax.swing.JButton jButton_home;
    private javax.swing.JComboBox<String> jComboBox_items;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_dispatch_row;
    private javax.swing.JLabel jLabel_item_name;
    private javax.swing.JLabel jLabel_mini_title;
    private javax.swing.JLabel jLabel_quantity;
    private javax.swing.JLabel jLabel_type;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea_title;
    private javax.swing.JTextField jTextField_item_name;
    private javax.swing.JTextField jTextField_item_quantity;
    private javax.swing.JTextField jTextField_row;
    // End of variables declaration//GEN-END:variables
}
