/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ice_6;

/**
 *
 * @author dylan
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home_Page
     */
    public Home() {
        initComponents(); 
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_home = new javax.swing.JButton();
        jButton_Dispatch_item = new javax.swing.JButton();
        jButton_Stock = new javax.swing.JButton();
        jButton_View_records = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_title = new javax.swing.JTextArea();
        jLabel_mini_title = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_introduction = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jButton_home.setBackground(new java.awt.Color(102, 102, 102));
        jButton_home.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_home.setForeground(new java.awt.Color(255, 255, 255));
        jButton_home.setText("Home");
        jButton_home.setBorder(null);
        jButton_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_homeActionPerformed(evt);
            }
        });

        jButton_Dispatch_item.setBackground(new java.awt.Color(102, 102, 102));
        jButton_Dispatch_item.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_Dispatch_item.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Dispatch_item.setText("Dispatch item");
        jButton_Dispatch_item.setBorder(null);
        jButton_Dispatch_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Dispatch_itemActionPerformed(evt);
            }
        });

        jButton_Stock.setBackground(new java.awt.Color(102, 102, 102));
        jButton_Stock.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_Stock.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Stock.setText("Stock");
        jButton_Stock.setBorder(null);
        jButton_Stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_StockActionPerformed(evt);
            }
        });

        jButton_View_records.setBackground(new java.awt.Color(102, 102, 102));
        jButton_View_records.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_View_records.setForeground(new java.awt.Color(255, 255, 255));
        jButton_View_records.setText("View records");
        jButton_View_records.setBorder(null);
        jButton_View_records.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_View_recordsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_View_records)
                    .addComponent(jButton_Stock)
                    .addComponent(jButton_Dispatch_item)
                    .addComponent(jButton_home))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jButton_home)
                .addGap(35, 35, 35)
                .addComponent(jButton_Dispatch_item)
                .addGap(35, 35, 35)
                .addComponent(jButton_Stock)
                .addGap(40, 40, 40)
                .addComponent(jButton_View_records)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jTextArea_title.setEditable(false);
        jTextArea_title.setBackground(new java.awt.Color(255, 51, 51));
        jTextArea_title.setColumns(20);
        jTextArea_title.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextArea_title.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_title.setRows(1);
        jTextArea_title.setText("Stock management system for covid-19 essentials");
        jScrollPane2.setViewportView(jTextArea_title);

        jLabel_mini_title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_mini_title.setText("Introduction");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Stock management");

        jTextArea_introduction.setColumns(20);
        jTextArea_introduction.setRows(5);
        jTextArea_introduction.setText("Welcome to the Stock Management System  \n\nThis application is designed to help you efficiently manage and track your stock inventory. \nWhether you're dispatching items, updating records, or simply viewing your stock, our system offers a user-friendly \ninterface to streamline your operations. \nFeatures:      \n\tRegistration/Login (Optional): Create an account or log in to access personalized features.     \n\tDispatch Items: Easily input item details to dispatch stock from your inventory.     \n\tCustom/Stock Page: Manage your stock or customize this page to suit your business needs.     \n\tView Records: Display all current stock and past transactions in an organized, easy-to-read format.  \n\nUse the navigation menu to explore the different features and get started managing your inventory today!");
        jScrollPane1.setViewportView(jTextArea_introduction);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_mini_title, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_mini_title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_homeActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_homeActionPerformed

    private void jButton_Dispatch_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Dispatch_itemActionPerformed
        // TODO add your handling code here:
        Dispatch_Item dispatch = new Dispatch_Item();
        dispatch.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_Dispatch_itemActionPerformed

    private void jButton_StockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_StockActionPerformed
        // TODO add your handling code here:
        Stock stock = new Stock();
        stock.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_StockActionPerformed

    private void jButton_View_recordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_View_recordsActionPerformed
        // TODO add your handling code here:
        Records record = new Records();
        record.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_View_recordsActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Dispatch_item;
    private javax.swing.JButton jButton_Stock;
    private javax.swing.JButton jButton_View_records;
    private javax.swing.JButton jButton_home;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_mini_title;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea_introduction;
    private javax.swing.JTextArea jTextArea_title;
    // End of variables declaration//GEN-END:variables
}
