/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ice_6;

/**
 *
 * @author dylan
 */
public class Stock extends javax.swing.JFrame {

    /**
     * Creates new form Home_Page
     */
    
    //set defualt stock values
        int Masks = 10059;
        int Hand_sanitizers = 12000;
        int Face_shields = 15000;
        int Disinfectant_wipes = 9560;
        
    public Stock() {
        initComponents(); 
        stockWindowDefualt();
    }
    
    //********************************************//
    //adjust stock window
    private void stockWindowDefualt()
    {
        //set loading variable incase slow processor
        jTextArea_stock.setText("Loading...");
        
        //set text 
        String message = "Stock values\n"
                + "*************************************************************\n"
                + "Masks                       : " + Masks + "\n"
                + "Hand_sanitizers       : " + Hand_sanitizers + "\n"
                + "Face_shields            : " + Face_shields + "\n"
                + "Disinfectant_wipes   : " + Disinfectant_wipes + "\n";
        
        jTextArea_stock.setText(message);
    }
    //*******************************************************//
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_home = new javax.swing.JButton();
        jButton_Dispatch_item = new javax.swing.JButton();
        jButton_Stock = new javax.swing.JButton();
        jButton_View_records = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_title = new javax.swing.JTextArea();
        jLabel_mini_title = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_stock = new javax.swing.JTextArea();
        jLabel_Item_selection = new javax.swing.JLabel();
        jComboBox_items1 = new javax.swing.JComboBox<>();
        jLabel_Amount = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButton_change_value = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jButton_home.setBackground(new java.awt.Color(102, 102, 102));
        jButton_home.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_home.setForeground(new java.awt.Color(255, 255, 255));
        jButton_home.setText("Home");
        jButton_home.setBorder(null);
        jButton_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_homeActionPerformed(evt);
            }
        });

        jButton_Dispatch_item.setBackground(new java.awt.Color(102, 102, 102));
        jButton_Dispatch_item.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_Dispatch_item.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Dispatch_item.setText("Dispatch item");
        jButton_Dispatch_item.setBorder(null);
        jButton_Dispatch_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Dispatch_itemActionPerformed(evt);
            }
        });

        jButton_Stock.setBackground(new java.awt.Color(102, 102, 102));
        jButton_Stock.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_Stock.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Stock.setText("Stock");
        jButton_Stock.setBorder(null);
        jButton_Stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_StockActionPerformed(evt);
            }
        });

        jButton_View_records.setBackground(new java.awt.Color(102, 102, 102));
        jButton_View_records.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_View_records.setForeground(new java.awt.Color(255, 255, 255));
        jButton_View_records.setText("View records");
        jButton_View_records.setBorder(null);
        jButton_View_records.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_View_recordsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_View_records)
                    .addComponent(jButton_Stock)
                    .addComponent(jButton_Dispatch_item)
                    .addComponent(jButton_home))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jButton_home)
                .addGap(35, 35, 35)
                .addComponent(jButton_Dispatch_item)
                .addGap(35, 35, 35)
                .addComponent(jButton_Stock)
                .addGap(40, 40, 40)
                .addComponent(jButton_View_records)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jTextArea_title.setEditable(false);
        jTextArea_title.setBackground(new java.awt.Color(255, 51, 51));
        jTextArea_title.setColumns(20);
        jTextArea_title.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextArea_title.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_title.setRows(1);
        jTextArea_title.setText("Stock management system for covid-19 essentials");
        jScrollPane2.setViewportView(jTextArea_title);

        jLabel_mini_title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_mini_title.setText("Stock/Inventory");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Stock management");

        jTextArea_stock.setColumns(20);
        jTextArea_stock.setRows(5);
        jTextArea_stock.setText("Welcome to the Stock Management System  \n\nThis application is designed to help you efficiently manage and track your stock inventory. \nWhether you're dispatching items, updating records, or simply viewing your stock, our system offers a user-friendly \ninterface to streamline your operations. \nFeatures:      \n\tRegistration/Login (Optional): Create an account or log in to access personalized features.     \n\tDispatch Items: Easily input item details to dispatch stock from your inventory.     \n\tCustom/Stock Page: Manage your stock or customize this page to suit your business needs.     \n\tView Records: Display all current stock and past transactions in an organized, easy-to-read format.  \n\nUse the navigation menu to explore the different features and get started managing your inventory today!");
        jScrollPane1.setViewportView(jTextArea_stock);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
        );

        jLabel_Item_selection.setText("Select Item");

        jComboBox_items1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masks", "Hand sanitizers", "Face shields", "Disinfectant wipes" }));
        jComboBox_items1.setToolTipText("");

        jLabel_Amount.setText("Increase or Decrease the Amount of that Item: ");

        jButton_change_value.setText("Make change");
        jButton_change_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_change_valueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel_mini_title, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(344, 344, 344))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_items1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Item_selection, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_change_value))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel_Amount)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_mini_title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Item_selection)
                            .addComponent(jLabel_Amount))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_items1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton_change_value, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_homeActionPerformed
        // TODO add your handling code here:
        Stock home = new Stock();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_homeActionPerformed

    private void jButton_Dispatch_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Dispatch_itemActionPerformed
        // TODO add your handling code here:
        Dispatch_Item dispatch = new Dispatch_Item();
        dispatch.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_Dispatch_itemActionPerformed

    private void jButton_StockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_StockActionPerformed
        // TODO add your handling code here:
        Stock stock = new Stock();
        stock.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_StockActionPerformed

    private void jButton_View_recordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_View_recordsActionPerformed
        // TODO add your handling code here:
        Records record = new Records();
        record.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_View_recordsActionPerformed

    private void jButton_change_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_change_valueActionPerformed
        // TODO add your handling code here:
        //code to change value
        // Get the selected item
    String selectedItem = (String) jComboBox_items1.getSelectedItem();
    
    // Get the new stock value from the spinner
    int newValue = (int) jSpinner1.getValue();
    
    // Update the appropriate stock value based on the selected item
    switch (selectedItem) {
        case "Masks":
            Masks += newValue;  // Increment or decrement Masks stock
            break;
        case "Hand sanitizers":
            Hand_sanitizers += newValue;  // Increment or decrement Hand sanitizers stock
            break;
        case "Face shields":
            Face_shields += newValue;  // Increment or decrement Face shields stock
            break;
        case "Disinfectant wipes":
            Disinfectant_wipes += newValue;  // Increment or decrement Disinfectant wipes stock
            break;
        default:
            break;
    }
    
    // Update the stock display
    stockWindowDefualt();
    }//GEN-LAST:event_jButton_change_valueActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Dispatch_item;
    private javax.swing.JButton jButton_Stock;
    private javax.swing.JButton jButton_View_records;
    private javax.swing.JButton jButton_change_value;
    private javax.swing.JButton jButton_home;
    private javax.swing.JComboBox<String> jComboBox_items1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Amount;
    private javax.swing.JLabel jLabel_Item_selection;
    private javax.swing.JLabel jLabel_mini_title;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea_stock;
    private javax.swing.JTextArea jTextArea_title;
    // End of variables declaration//GEN-END:variables
}
