/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Question3;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author dylan
 */
public class Travel_Log extends javax.swing.JFrame {

    /**
     * Creates new form Travel_Log
     */
    public Travel_Log() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStart = new javax.swing.JLabel();
        lblEnd = new javax.swing.JLabel();
        lblTravel = new javax.swing.JLabel();
        cmbStartLocation = new javax.swing.JComboBox<>();
        cmbEndLocation = new javax.swing.JComboBox<>();
        cmbTravelBy = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaTravelLog = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Travel Log");

        lblStart.setText("Start Location:");

        lblEnd.setText("End Location:");

        lblTravel.setText("Travel By:");

        cmbStartLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cape Town", "Durban", "Port Elizabeth" }));

        cmbEndLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cape Town", "Durban", "Port Elizabeth" }));

        cmbTravelBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Airplane", "Train" }));

        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        txaTravelLog.setColumns(20);
        txaTravelLog.setRows(5);
        jScrollPane1.setViewportView(txaTravelLog);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblStart, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbStartLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbEndLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTravel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbTravelBy, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStart)
                    .addComponent(cmbStartLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnd)
                    .addComponent(cmbEndLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTravel)
                    .addComponent(cmbTravelBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSubmit)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        
        //*************************************************//
        //make sure start and end location are different
        String start = cmbStartLocation.getSelectedItem().toString();
        String end = cmbEndLocation.getSelectedItem().toString();
        
        if(!start.equals(end))
        {
            //*************************************************//
            //save values to travel.txt
            saveValues();
            //*************************************************//
        
            //*************************************************//
            //populate the list box
            populateListBox();
            //*************************************************//
        }
        else
        {
            //if_ they are the same show an error
            JOptionPane.showMessageDialog(null, "Destinations cannot be the same!!!");
        }
        
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Travel_Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Travel_Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Travel_Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Travel_Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Travel_Log().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cmbEndLocation;
    private javax.swing.JComboBox<String> cmbStartLocation;
    private javax.swing.JComboBox<String> cmbTravelBy;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnd;
    private javax.swing.JLabel lblStart;
    private javax.swing.JLabel lblTravel;
    private javax.swing.JTextArea txaTravelLog;
    // End of variables declaration//GEN-END:variables

    //*************************************************//
    private void saveValues() 
    {
        //*************************************************//
        //make values local variables
        String start = cmbStartLocation.getSelectedItem().toString();
        String end = cmbEndLocation.getSelectedItem().toString();
        String travel = cmbTravelBy.getSelectedItem().toString();
        //*************************************************//
        
        //*************************************************//
        //create print writer to override the text file with new information
        try (PrintWriter writer = new PrintWriter(new FileWriter("travel.txt"))) {
            //*************************************************//
            
            //*************************************************//
            //write text to the file
            writer.println(start);
            writer.println(end);
            writer.println("Travel By: " + travel);
            //*************************************************//
            
            //*************************************************//
            //close writer
            writer.close();
            //*************************************************//
            
        } catch (IOException e) 
        {
            e.printStackTrace();
        }
        //*************************************************//
    }
    //*************************************************//

    //*************************************************//
    private void populateListBox()
    {
        //*************************************************//
        //create title 
        String title = "TRAVEL LOG";
        //create comment_ lines
        String comments = "**************************************";
        //create message 
        String message;
        //destination count
        int count = 1;
        //*************************************************//
        
        //*************************************************//
        //start message
        message = title + "\n";
        message += comments + "\n";
        //*************************************************//
        
        //*************************************************//
        //create scan object and read from file
        try {
            //*************************************************//
            // Create a File object for the text file
            File file = new File("travel.txt");
            //*************************************************//
            
            //*************************************************//
            // Pass the File object to the Scanner
            Scanner scan = new Scanner(file);
            //*************************************************//
            
            //*************************************************//
            // Read the contents of the file
            while (scan.hasNextLine())
            {
                //*************************************************//
                //take lines from the text file
                message += "Destination " + count + ": " + scan.nextLine() + "\n";
                count++;
                
                //next destination
                message += "Destination " + count + ": " + scan.nextLine() + "\n";
                count++;
                
                //travel by
                message += scan.nextLine() + "\n";
                //*************************************************//
            }
            //*************************************************//
            
            //*************************************************//
            // Close the scanner
            scan.close();
            //*************************************************//
            
            //*************************************************//
            //finish the message
            message += comments;
            //*************************************************//
            
            //*************************************************//
            //update list box
            txaTravelLog.setText(message);
            //*************************************************//
            
        } catch (FileNotFoundException ex) {
            
            }
        }
    //*************************************************//
}
//***********************************END OF FILE****************************************//