/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Question_1;

import javax.swing.JOptionPane;

/**
 *
 * @author dylan
 */
public class costOfMusicalLessonsGUI extends javax.swing.JFrame {

    /**
     * Creates new form costOfMusicalLessonsGUI
     */
    public costOfMusicalLessonsGUI() {
        initComponents();
    }

    //*************************************************//
    //declare array of cost 
    static int[][] costOfLessons = {{150, 250, 280}
                            ,{215, 232, 280}
                            ,{130, 185, 310}};
    //*************************************************//
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblINSTRUMENT = new javax.swing.JLabel();
        lblLEVEL = new javax.swing.JLabel();
        cmbINSTRUMENT = new javax.swing.JComboBox<>();
        cmbLEVEL = new javax.swing.JComboBox<>();
        btnSUBMIT = new javax.swing.JButton();
        btnREPORT = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Musical Lessons");

        lblINSTRUMENT.setText("INSTRUMENT:");

        lblLEVEL.setText("LEVEL:");

        cmbINSTRUMENT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guitar", "Piano", "Violin" }));

        cmbLEVEL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beginner", "Intermediate", "Advanced" }));

        btnSUBMIT.setText("SUBMIT");
        btnSUBMIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSUBMITActionPerformed(evt);
            }
        });

        btnREPORT.setText("REPORT");
        btnREPORT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnREPORTActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("EXIT");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tools");

        jMenuItem2.setText("Submit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Report");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblINSTRUMENT, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbINSTRUMENT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLEVEL, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSUBMIT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnREPORT))
                            .addComponent(cmbLEVEL, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblINSTRUMENT)
                    .addComponent(cmbINSTRUMENT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLEVEL)
                    .addComponent(cmbLEVEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSUBMIT)
                    .addComponent(btnREPORT))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSUBMITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSUBMITActionPerformed
        // TODO add your handling code here:
        
        //*************************************************//
        // PRINT cost of lesson
        determineLessonCost();
        //*************************************************//
    }//GEN-LAST:event_btnSUBMITActionPerformed

    private void btnREPORTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnREPORTActionPerformed
        // TODO add your handling code here:
        //*************************************************//
        //display average cost of lessons
        displayAverageLessonCost();
        //*************************************************//
    }//GEN-LAST:event_btnREPORTActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        //*************************************************//
        //exit application
        JOptionPane.showMessageDialog(null, "Thank you, goodbye!");
        System.exit(0);
        //*************************************************//
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        //*************************************************//
        // PRINT cost of lesson
        determineLessonCost();
        //*************************************************//
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        //*************************************************//
        //display average cost of lessons
        displayAverageLessonCost();
        //*************************************************//
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(costOfMusicalLessonsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(costOfMusicalLessonsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(costOfMusicalLessonsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(costOfMusicalLessonsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new costOfMusicalLessonsGUI().setVisible(true);
            }
        });
    }
    
    //*************************************************//
    //method to find the cost of lessons
    private void determineLessonCost()
    {
        //*************************************************//
        //get the cost value from the GUI
        int level = cmbLEVEL.getSelectedIndex();
        int instrument = cmbINSTRUMENT.getSelectedIndex();
        
        int cost = costOfLessons[level][instrument];
        //*************************************************//
        
        //*************************************************//
        //string message to display
        String message = "";
        message = "INSTRUMENT: " + cmbINSTRUMENT.getSelectedItem().toString() + "\n";
        message += "LEVEL: " + cmbLEVEL.getSelectedItem().toString() + "\n";
        message += "LESSON PRICE: R " + cost;
        //*************************************************//
        
        //*************************************************//
        //display lesson cost
        JOptionPane.showMessageDialog(
            null, 
            message, 
            "Music Lessons Price", 
            JOptionPane.INFORMATION_MESSAGE
        );
        //*************************************************//
    }
    //*************************************************//

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnREPORT;
    private javax.swing.JButton btnSUBMIT;
    private javax.swing.JComboBox<String> cmbINSTRUMENT;
    private javax.swing.JComboBox<String> cmbLEVEL;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel lblINSTRUMENT;
    private javax.swing.JLabel lblLEVEL;
    // End of variables declaration//GEN-END:variables

    //*************************************************//
    //average cost of lessons
    private void displayAverageLessonCost() 
    {
        
        //*************************************************//
        //string messages for beginner 
        String beginner = "Average lesson price for Beginner: R ";
        String intermediate = "Average lesson price for Intermediate: R ";
        String advanced = "Average lesson price for Advanced: R ";
        //*************************************************//
        
        //*************************************************//
        //create integer values for the averages
        int beginAVG = 0;
        int interAVG = 0;
        int advanAVG = 0;
        
        for (int i = 0; i < costOfLessons.length; i++)
        {
            beginAVG += costOfLessons[0][i];
            interAVG += costOfLessons[1][i];
            advanAVG += costOfLessons[2][i];
        }
        
        beginAVG = beginAVG/costOfLessons.length;
        interAVG = interAVG/costOfLessons.length;
        advanAVG = advanAVG/costOfLessons.length;
        //*************************************************//
        
        //*************************************************//
        //create message 
        String message = "";
        message = beginner + beginAVG + "\n";
        message += intermediate + interAVG + "\n";
        message += advanced + advanAVG + "\n";
        //*************************************************//
        
        //*************************************************//
        //display average lesson cost
        JOptionPane.showMessageDialog(
            null, 
            message, 
            "Message", 
            JOptionPane.INFORMATION_MESSAGE
        );
        //*************************************************//
    }
    //*************************************************//
}
