/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Question_2;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author dylan
 */
public class TechnicianGUI extends javax.swing.JFrame {

    /**
     * Creates new form TechnicianGUI
     */
    public TechnicianGUI() {
        initComponents();
    }
    //*************************************************//
    //craete technician object
    Technician technician = new Technician();
    //*************************************************//

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        lblTECHNICIAN_NAME = new javax.swing.JLabel();
        lblTECHNICIAN_LOCATION = new javax.swing.JLabel();
        lblREPAIR_COST = new javax.swing.JLabel();
        lblTECHNICIAN_RATE = new javax.swing.JLabel();
        lblTECHNICIAN_REPORT = new javax.swing.JLabel();
        cmbLocations = new javax.swing.JComboBox<>();
        txtName = new javax.swing.JTextField();
        txtCost = new javax.swing.JTextField();
        txtRate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaReport = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnProcessReport = new javax.swing.JMenuItem();
        btnClear = new javax.swing.JMenuItem();
        btnSaveReport = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TECHNICIAN");

        lblTECHNICIAN_NAME.setText("TECHNICIAN NAME:");

        lblTECHNICIAN_LOCATION.setText("TECHNICIAN LOCATION:");

        lblREPAIR_COST.setText("REPAIR COST:");

        lblTECHNICIAN_RATE.setText("TECHNICIAN RATE:");

        lblTECHNICIAN_REPORT.setText("TECHNICIAN REPORT:");

        cmbLocations.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cape Town", "Durban", "Pretoria" }));

        txaReport.setEditable(false);
        txaReport.setColumns(20);
        txaReport.setRows(5);
        jScrollPane1.setViewportView(txaReport);

        jMenu1.setText("File");

        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jMenu1.add(btnExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tools");

        btnProcessReport.setText("Process Report");
        btnProcessReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessReportActionPerformed(evt);
            }
        });
        jMenu2.add(btnProcessReport);

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jMenu2.add(btnClear);

        btnSaveReport.setText("Save Report");
        btnSaveReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveReportActionPerformed(evt);
            }
        });
        jMenu2.add(btnSaveReport);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTECHNICIAN_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTECHNICIAN_LOCATION, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbLocations, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblREPAIR_COST, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCost))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTECHNICIAN_RATE, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtRate))
                    .addComponent(lblTECHNICIAN_REPORT, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTECHNICIAN_LOCATION)
                    .addComponent(cmbLocations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTECHNICIAN_NAME)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblREPAIR_COST)
                    .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTECHNICIAN_RATE)
                    .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblTECHNICIAN_REPORT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        //*************************************************//
        //exit application 
        System.exit(0);
        //*************************************************//
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnProcessReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessReportActionPerformed
        // TODO add your handling code here:
        
        String message = reportMessage();
        
        //*************************************************//
        //set display to message
        txaReport.setText(message);
        //*************************************************//
    }//GEN-LAST:event_btnProcessReportActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        //*************************************************//
        //clear values
        cmbLocations.setSelectedIndex(0);
        txtCost.setText("");
        txtName.setText("");
        txtRate.setText("");
        txaReport.setText("");
        //*************************************************//
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSaveReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveReportActionPerformed
        // TODO add your handling code here:
        //*************************************************//
        //save report
         // TODO add your handling code here:
    //*************************************************//
    // Get the report content from the text area
    String reportContent = txaReport.getText();
        
        try {
            // Create a FileWriter to write the report content to the selected file
            BufferedWriter writer = new BufferedWriter(new FileWriter("save.txt"));
            
            // Write the content to the file
            writer.write(reportContent);
            
            // Close the writer
            writer.close();
            
            // Optionally, show a message that the file was saved
            JOptionPane.showMessageDialog(this, "Report saved successfully.");
        } catch (IOException e) {
            // Handle any IO exceptions
            JOptionPane.showMessageDialog(this, "Error saving report: " + e.getMessage());
        }
    
    //*************************************************//
        //*************************************************//
    }//GEN-LAST:event_btnSaveReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TechnicianGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TechnicianGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TechnicianGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TechnicianGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TechnicianGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnClear;
    private javax.swing.JMenuItem btnExit;
    private javax.swing.JMenuItem btnProcessReport;
    private javax.swing.JMenuItem btnSaveReport;
    private javax.swing.JComboBox<String> cmbLocations;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblREPAIR_COST;
    private javax.swing.JLabel lblTECHNICIAN_LOCATION;
    private javax.swing.JLabel lblTECHNICIAN_NAME;
    private javax.swing.JLabel lblTECHNICIAN_RATE;
    private javax.swing.JLabel lblTECHNICIAN_REPORT;
    private javax.swing.JTextArea txaReport;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRate;
    // End of variables declaration//GEN-END:variables

    private String reportMessage() {
        
        //*************************************************//
        //get string values
        String location = cmbLocations.getSelectedItem().toString();
        String name = txtName.getText();
        String cost = txtCost.getText();
        String rate = txtRate.getText();
        //*************************************************//
        
        //*************************************************//
        //calculate pay
        double pay = technician.CalculatePay(cost, rate);
        //*************************************************//
        
        //*************************************************//
        //create message
        String message = "TECHNICIAN LOCATION: " + location + "\n";
        message += "TECHNICIAN NAME: " + name + "\n";
        message += "REPAIR COST: R" + cost + "\n";
        message += "TECHNICIAN RATE: " + rate + "%\n";
        message += "CALCULATED PAY: R " + pay;
        //*************************************************//
        
        return message;
    }
    //*************************************************//
}
//***********************************END OF FILE****************************************//